console.log("Starting my Node JS Project");
console.log("Travel Booking App");
const travel = require("./Glenn_TravelBooking.js");
console.log("Full experience list: ", travel.listExperiences());
console.log(travel.addExperience("Shinkansen One Way Tokyo to Osaka", "Japan", "Train Ticket", "Tokyo Station", "World fastest train ride", 200));
console.log(travel.findByLocation("Tokyo"));
console.log(travel.findByCountry("Singapore"));
console.log(travel.updateExPrice("Tokyo 8 Day Tour", 5000));
console.log(travel.findByLocation("Tokyo"));
console.log(travel.deleteExperience("Tokyo 8 Day Tour"));
console.log("Full experience list: ", travel.listExperiences());